server:
    port: 8888


elaparato:
    keycloak:
        serverUrl: http://localhost:8080
        realm: elaparato-molinafederico
        clientId: api-client
        clientSecret: "5zZLh8tJQWLQmtOGIYjfqb509A7uAHf2"

spring:
    application:
        name: elaparato
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/elaparato-molinafederico

    datasource:
        url: jdbc:mysql://localhost:3306/elaparato?createDatabaseIfNotExist=true
        username: root
        password: "MySQL22*"
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            show-sql: true

